Refactor applogic (#140)

diff --git a/prototype/makefile b/prototype/makefile
--- a/prototype/makefile
+++ b/prototype/makefile
@@ -27,6 +27,25 @@ clean:
 	dart pub upgrade
 	cd $(RUST_BASE_DIR) ; cargo clean
 
+# Define a target that checks for uncommitted changes
+check-git-clean:
+	@if ! git diff-index --quiet HEAD --; then \
+		echo "Error: You have uncommitted changes. Please commit or stash them before proceeding."; \
+		exit 1; \
+	fi
+
+frb-integrate: check-git-clean
+	mv flutter_rust_bridge.yaml flutter_rust_bridge.yaml.tmp
+	rm -Rf  rust_builder test_driver
+	flutter_rust_bridge_codegen integrate --rust-crate-name phnxapplogic --rust-crate-dir ../applogic
+	git restore --source=HEAD --staged --worktree ../applogic lib
+	git clean -fd ../applogic lib
+	mv flutter_rust_bridge.yaml flutter_rust_bridge.yaml.generated.tmp
+	echo "# This is only to inspect the generated flutter_rust_bridge.yaml file. Remove if not needed." > /tmp/header.tmp
+	cat /tmp/header.tmp flutter_rust_bridge.yaml.generated.tmp >> flutter_rust_bridge.yaml.generated
+	mv flutter_rust_bridge.yaml.tmp flutter_rust_bridge.yaml
+	rm flutter_rust_bridge.yaml.generated.tmp
+
 setup-ci:
 	curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
 	cargo binstall -y flutter_rust_bridge_codegen@2.0.0-dev.37
@@ -37,6 +56,7 @@ dart-bridge:
 	rm -f $(RUST_BASE_DIR)/src/frb_*.rs
 	touch $(RUST_BASE_DIR)/src/frb_generated.rs
 	mkdir -p lib/core
+	rm -Rf lib/core/*
 	flutter pub get
 	flutter_rust_bridge_codegen generate
 
